[package]
name = "boom"
version = "0.1.2"
authors = ["hhatto <hhatto.jp@gmail.com>"]

[dependencies]
getopts = "*"
hyper = "*"
time = "*"
mime = "*"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[[bin]]
name = "boom-rust"
path = "src/main.rs"
